name: Deploy to AWS Lambda
on:
  push:
    branches:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment
        run: uv venv
        
      - name: Install dependencies into ./package
        run: |
          uv pip install . --target ./package
          
      - name: Copy Lambda function into ./package
        run: |
          cp lambda_function.py package/
          cp -r data_processing/ package/data_processing/
          cp -r prompt/ package/prompt/
          cp -r text_extractor/ package/text_extractor/
      - name: Zip package into lambda.zip
        run: |
          cd package && zip -r ../lambda.zip .
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name arn:aws:lambda:eu-north-1:771936571040:function:Contract_Analyzer --zip-file fileb://lambda.zip
